# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Iznajmi sto za stoni tenis u Novom Sadu
author: >-
  Ovu uslugu vam pruža:<br>
  <b>Trk inovacije doo</b> Novi Sad<br>
  Nova 3, broj 9, Novi Sad<br>
  Telefon <a href='tel:0637298539'>063 7298539</a>
description: >- # this means to ignore newlines until "baseurl:"
  Obezbedite dobru rekreaciju za vas i vašu decu tako što ćete iznajmiti sto za
  stoni tenis. Isporuka i preuzimanje na vašoj adresi ili biloj kojoj drugoj
  lokaciji na području Novog Sada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iznajmi-sto-za-stoni-tenis-novi-sad.trk.in.rs" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-36706408-6

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
